name: make-release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * *  */7"

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: ^1.24
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on V$(date +%Y.%m.%d)" >> $GITHUB_ENV
          echo "TAG_NAME=V$(date +%Y.%m.%d)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@main
  
      - name: Get project dependencies & run
        run: |
          echo "Downloading dependencies..."
          for i in {1..5}; do go mod download && break || sleep 15; done
          make release -j$(nproc)
          
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: ${{ env.TAG_NAME }}
          file: ./trojan-go-*.zip
          file_glob: true
          
    # 删除无用 workflow runs;
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 0.1
          keep_minimum_runs: 1
